project_id = "ltttwatjtvnnkxmhxnoc"

[functions.generate-model-answer]
verify_jwt = true

[functions.summarize-news]
verify_jwt = true

[functions.essay-feedback]
verify_jwt = true

[functions.generate-essay]
verify_jwt = true
